### ISSUE TITLE
Windows Defender kill the ProcessHollowing.exe

### ISSUE THREAD

**Issue by highwayMo** [m0n0ph1/Process-Hollowing#6]
I have complied this item completely and get `ProcessHollowing.exe,HelloWorld.exe`.When i execute the ProcessHollowing.exe,the Windows Defender warnned ProcessHollowing.exe is a Trojan and killed it.

**Comment by CCCougar** [comment]
You have the source code in your hand. By reading the source code, you will naturally know whether the compiled program is a Trojan, so you can decide whether to run the program compiled from this source code. If you want to learn by running the program, in order to avoid Windows Defender, you can turn off the real-time protection of Windows Defender.

**Comment by Denzerson1** [comment]
Are you retarded?
